final List<Map<String, String>> imagePaths = [
  {
    'image': 'assets/image/image copy 2.png',
    'title': 'Deadpool & Wolverine',
    'year': '2024',
    'duration': '2h 30m',
    'rating': 'R',
    'director': 'Shawn Levy',
    'studio': 'Marvel Studios',
    'genre': 'Action, Comedy',
  },
  {
    'image': 'assets/image/image copy 3.png',
    'title': 'Inside Out 2',
    'year': '2024',
    'duration': '1h 50m',
    'rating': 'PG',
    'director': 'Kelsey Mann',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/image/image copy 4.png',
    'title': 'Despicable Me 4',
    'year': '2024',
    'duration': '1h 40m',
    'rating': 'PG',
    'director': 'Kyle Balda',
    'studio': 'Illumination Entertainment',
    'genre': 'Animation, Comedy',
  },
  {
    'image': 'assets/image/image copy 5.png',
    'title': 'Twisters',
    'year': '2024',
    'duration': '2h 10m',
    'rating': 'PG-13',
    'director': 'Lee Isaac Chung',
    'studio': 'Universal Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/image/image copy 6.png',
    'title': 'Ozi: Voice of the Forest',
    'year': '2024',
    'duration': '1h 30m',
    'rating': 'PG',
    'director': 'Tim Harper',
    'studio': 'DreamWorks Animation',
    'genre': 'Animation, Fantasy',
  },
  {
    'image': 'assets/image/image copy 7.png',
    'title': 'Megalopolis',
    'year': '2024',
    'duration': '2h 45m',
    'rating': 'R',
    'director': 'Francis Ford Coppola',
    'studio': 'Zoetrope Studios',
    'genre': 'Drama, Sci-Fi',
  },
  {
    'image': 'assets/image/image copy 8.png',
    'title': 'Flight Risk',
    'year': '2024',
    'duration': '2h 00m',
    'rating': 'PG-13',
    'director': 'Matt Reeves',
    'studio': 'Warner Bros.',
    'genre': 'Thriller, Action',
  },
  {
    'image': 'assets/image/image copy 9.png',
    'title': 'The Marvels',
    'year': '2024',
    'duration': '2h 15m',
    'rating': 'PG-13',
    'director': 'Nia DaCosta',
    'studio': 'Marvel Studios',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/image/image copy 10.png',
    'title': 'Spider-Man: Beyond',
    'year': '2024',
    'duration': '2h 20m',
    'rating': 'PG-13',
    'director': 'Jon Watts',
    'studio': 'Sony Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/image/image copy 11.png',
    'title': 'Elemental',
    'year': '2024',
    'duration': '1h 45m',
    'rating': 'PG',
    'director': 'Peter Sohn',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/image/image copy 12.png',
    'title': 'Barbie',
    'year': '2023',
    'duration': '1h 54m',
    'rating': 'PG-13',
    'director': 'Greta Gerwig',
    'studio': 'Warner Bros.',
    'genre': 'Comedy, Fantasy',
  },
  {
    'image': 'assets/image/image copy 13.png',
    'title': 'Indiana Jones 5',
    'year': '2023',
    'duration': '2h 34m',
    'rating': 'PG-13',
    'director': 'James Mangold',
    'studio': 'Lucasfilm',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/image/image copy 14.png',
    'title': 'The Flash',
    'year': '2023',
    'duration': '2h 24m',
    'rating': 'PG-13',
    'director': 'Andy Muschietti',
    'studio': 'Warner Bros.',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/image/image copy 15.png',
    'title': 'Guardians of the Galaxy Vol. 3',
    'year': '2023',
    'duration': '2h 30m',
    'rating': 'PG-13',
    'director': 'James Gunn',
    'studio': 'Marvel Studios',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/image/image copy 16.png',
    'title': 'The Little Mermaid',
    'year': '2023',
    'duration': '2h 15m',
    'rating': 'PG',
    'director': 'Rob Marshall',
    'studio': 'Disney',
    'genre': 'Family, Fantasy',
  },
  {
    'image': 'assets/image/image copy.png',
    'title': 'The Hunger Games',
    'year': '2023',
    'duration': '2h 20m',
    'rating': 'PG-13',
    'director': 'Francis Lawrence',
    'studio': 'Lionsgate',
    'genre': 'Action, Drama',
  },
  {
    'image': 'assets/image/image.png',
    'title': 'Transformers: Rise of the Beasts',
    'year': '2023',
    'duration': '2h 07m',
    'rating': 'PG-13',
    'director': 'Steven Caple Jr.',
    'studio': 'Paramount Pictures',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/image/kingdom.png',
    'title': 'The Kingdom',
    'year': '2023',
    'duration': '2h 10m',
    'rating': 'R',
    'director': 'Gavin O’Connor',
    'studio': 'Netflix',
    'genre': 'Drama, Thriller',
  },
  {
    'image': 'assets/image/vgful34.png',
    'title': 'Vanguard',
    'year': '2023',
    'duration': '1h 48m',
    'rating': 'PG-13',
    'director': 'Stanley Tong',
    'studio': 'China Film Group',
    'genre': 'Action, Adventure',
  },
];

final List<Map<String, String>> imageAnimationPaths = [
  {
    'image': 'assets/post/animation/image copy 2.png',
    'title': 'Nana',
    'year': '2024',
    'duration': '2h 30m',
    'rating': 'R',
    'director': 'Shawn Levy',
    'studio': 'Marvel Studios',
    'genre': 'Action, Comedy',
    'url': "assets/video/pka1tong.MP4"
  },
  {
    'image': 'assets/post/animation/image copy 3.png',
    'title': 'Angela',
    'year': '2024',
    'duration': '1h 50m',
    'rating': 'PG',
    'director': 'Kelsey Mann',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/post/animation/image copy 4.png',
    'title': 'Despicable Me 4',
    'year': '2024',
    'duration': '1h 40m',
    'rating': 'PG',
    'director': 'Kyle Balda',
    'studio': 'Illumination Entertainment',
    'genre': 'Animation, Comedy',
  },
  {
    'image': 'assets/post/animation/image copy 5.png',
    'title': 'Twisters',
    'year': '2024',
    'duration': '2h 10m',
    'rating': 'PG-13',
    'director': 'Lee Isaac Chung',
    'studio': 'Universal Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/post/animation/image copy 6.png',
    'title': 'Ozi: Voice of the Forest',
    'year': '2024',
    'duration': '1h 30m',
    'rating': 'PG',
    'director': 'Tim Harper',
    'studio': 'DreamWorks Animation',
    'genre': 'Animation, Fantasy',
  },
  {
    'image': 'assets/post/animation/image copy 7.png',
    'title': 'Megalopolis',
    'year': '2024',
    'duration': '2h 45m',
    'rating': 'R',
    'director': 'Francis Ford Coppola',
    'studio': 'Zoetrope Studios',
    'genre': 'Drama, Sci-Fi',
  },
  {
    'image': 'assets/post/animation/image copy 8.png',
    'title': 'Flight Risk',
    'year': '2024',
    'duration': '2h 00m',
    'rating': 'PG-13',
    'director': 'Matt Reeves',
    'studio': 'Warner Bros.',
    'genre': 'Thriller, Action',
  },
  {
    'image': 'assets/post/animation/image copy 9.png',
    'title': 'The Marvels',
    'year': '2024',
    'duration': '2h 15m',
    'rating': 'PG-13',
    'director': 'Nia DaCosta',
    'studio': 'Marvel Studios',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/post/animation/image copy 10.png',
    'title': 'Spider-Man: Beyond',
    'year': '2024',
    'duration': '2h 20m',
    'rating': 'PG-13',
    'director': 'Jon Watts',
    'studio': 'Sony Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/post/animation/image copy 11.png',
    'title': 'Elemental',
    'year': '2024',
    'duration': '1h 45m',
    'rating': 'PG',
    'director': 'Peter Sohn',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/post/animation/image copy.png',
    'title': 'Barbie',
    'year': '2023',
    'duration': '1h 54m',
    'rating': 'PG-13',
    'director': 'Greta Gerwig',
    'studio': 'Warner Bros.',
    'genre': 'Comedy, Fantasy',
  },
  {
    'image': 'assets/image/image copy 13.png',
    'title': 'Indiana Jones 5',
    'year': '2023',
    'duration': '2h 34m',
    'rating': 'PG-13',
    'director': 'James Mangold',
    'studio': 'Lucasfilm',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/post/animation/image.png',
    'title': 'The Flash',
    'year': '2023',
    'duration': '2h 24m',
    'rating': 'PG-13',
    'director': 'Andy Muschietti',
    'studio': 'Warner Bros.',
    'genre': 'Action, Sci-Fi',
  },
];

final List<Map<String, String>> imageRomancePaths = [
  {
    'image': 'assets/homeimage/row/image copy 2.png',
    'title': 'Deadpool & Wolverine',
    'year': '2024',
    'duration': '2h 30m',
    'rating': 'R',
    'director': 'Shawn Levy',
    'studio': 'Marvel Studios',
    'genre': 'Action, Comedy',
  },
  {
    'image': 'assets/homeimage/row/image copy 3.png',
    'title': 'Inside Out 2',
    'year': '2024',
    'duration': '1h 50m',
    'rating': 'PG',
    'director': 'Kelsey Mann',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/homeimage/row/image copy 4.png',
    'title': 'Despicable Me 4',
    'year': '2024',
    'duration': '1h 40m',
    'rating': 'PG',
    'director': 'Kyle Balda',
    'studio': 'Illumination Entertainment',
    'genre': 'Animation, Comedy',
  },
  {
    'image': 'assets/homeimage/row/image copy 5.png',
    'title': 'Twisters',
    'year': '2024',
    'duration': '2h 10m',
    'rating': 'PG-13',
    'director': 'Lee Isaac Chung',
    'studio': 'Universal Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/homeimage/row/image copy 6.png',
    'title': 'Ozi: Voice of the Forest',
    'year': '2024',
    'duration': '1h 30m',
    'rating': 'PG',
    'director': 'Tim Harper',
    'studio': 'DreamWorks Animation',
    'genre': 'Animation, Fantasy',
  },
  {
    'image': 'assets/homeimage/row/image copy 7.png',
    'title': 'Megalopolis',
    'year': '2024',
    'duration': '2h 45m',
    'rating': 'R',
    'director': 'Francis Ford Coppola',
    'studio': 'Zoetrope Studios',
    'genre': 'Drama, Sci-Fi',
  },
  {
    'image': 'assets/homeimage/row/image copy 8.png',
    'title': 'Flight Risk',
    'year': '2024',
    'duration': '2h 00m',
    'rating': 'PG-13',
    'director': 'Matt Reeves',
    'studio': 'Warner Bros.',
    'genre': 'Thriller, Action',
  },
  {
    'image': 'assets/homeimage/row/image copy 9.png',
    'title': 'The Marvels',
    'year': '2024',
    'duration': '2h 15m',
    'rating': 'PG-13',
    'director': 'Nia DaCosta',
    'studio': 'Marvel Studios',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/homeimage/row/image copy 10.png',
    'title': 'Spider-Man: Beyond',
    'year': '2024',
    'duration': '2h 20m',
    'rating': 'PG-13',
    'director': 'Jon Watts',
    'studio': 'Sony Pictures',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/homeimage/row/image copy 11.png',
    'title': 'Elemental',
    'year': '2024',
    'duration': '1h 45m',
    'rating': 'PG',
    'director': 'Peter Sohn',
    'studio': 'Pixar Animation Studios',
    'genre': 'Animation, Family',
  },
  {
    'image': 'assets/homeimage/row/image copy 12.png',
    'title': 'Barbie',
    'year': '2023',
    'duration': '1h 54m',
    'rating': 'PG-13',
    'director': 'Greta Gerwig',
    'studio': 'Warner Bros.',
    'genre': 'Comedy, Fantasy',
  },
  {
    'image': 'assets/homeimage/row/image copy 13.png',
    'title': 'Indiana Jones 5',
    'year': '2023',
    'duration': '2h 34m',
    'rating': 'PG-13',
    'director': 'James Mangold',
    'studio': 'Lucasfilm',
    'genre': 'Action, Adventure',
  },
  {
    'image': 'assets/homeimage/row/image copy 14.png',
    'title': 'The Flash',
    'year': '2023',
    'duration': '2h 24m',
    'rating': 'PG-13',
    'director': 'Andy Muschietti',
    'studio': 'Warner Bros.',
    'genre': 'Action, Sci-Fi',
  },
  {
    'image': 'assets/homeimage/row/image copy.png',
    'title': 'The Hunger Games',
    'year': '2023',
    'duration': '2h 20m',
    'rating': 'PG-13',
    'director': 'Francis Lawrence',
    'studio': 'Lionsgate',
    'genre': 'Action, Drama',
  },
  {
    'image': 'assets/homeimage/row/image.png',
    'title': 'Transformers: Rise of the Beasts',
    'year': '2023',
    'duration': '2h 07m',
    'rating': 'PG-13',
    'director': 'Steven Caple Jr.',
    'studio': 'Paramount Pictures',
    'genre': 'Action, Sci-Fi',
  },
];
